Intermediate step. Should not save everything
There is simply too much stuff here. And most of it is even useless

diff --git a/bin/move_runs_to_data b/bin/move_runs_to_data
--- a/bin/move_runs_to_data
+++ b/bin/move_runs_to_data
@@ -1,29 +1,107 @@
-#!/bin/bash
+#!/usr/bin/env bash
+# Based on: https://betterdev.blog/minimal-safe-bash-script-template/
+set -Eeuo pipefail
+trap cleanup SIGINT SIGTERM ERR EXIT
 
-# create script to move stuff
+script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
 
-if [[ -d $1 ]]
-then
-    echo "/etc exists on your filesystem."
-fi
+usage() {
+  cat << EOF
+Usage: $(basename "${BASH_SOURCE[0]}") [-h] [-v] [-f] -p param_value arg1 [arg2...]
 
+This script is used to move data from the seu directory, to the data directory in this project.
+It then unpacks all of the data in the data directory.
 
-a_flag=''
-b_flag=''
-files=''
-verbose='false'
+Available options:
 
-print_usage() {
-  printf "Usage: ..."
+-h, --help          Print this help and exit
+-v, --verbose       Print script debug info
+-r, --remove        If the script should remove the files from the source dir (default remove data)
+-s, --source        Path to dir to move data from (default '/tools/SoCMake-Ibex/vrf/uvm/build/seu_regress_coremark/')
+-d, --destination   Path to dir to move data to (defulat $(dirname "${script_dir}")/data)
+
+EOF
+  exit
 }
 
-while getopts 'abf:v' flag; do
-  case "${flag}" in
-    a) a_flag='true' ;;
-    b) b_flag='true' ;;
-    f) files="${OPTARG}" ;;
-    v) verbose='true' ;;
-    *) print_usage
-       exit 1 ;;
-  esac
+cleanup() {
+  trap - SIGINT SIGTERM ERR EXIT
+  # script cleanup here
+}
+
+setup_colors() {
+  if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
+    NOFORMAT='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
+  else
+    NOFORMAT='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
+  fi
+}
+
+msg() {
+  echo >&2 -e "${1-}"
+}
+
+die() {
+  local msg=$1
+  local code=${2-1} # default exit status 1
+  msg "$msg"
+  exit "$code"
+}
+
+parse_params() {
+  # default values of variables set from params
+  remove=1
+  source='/tools/SoCMake-Ibex/vrf/uvm/build/seu_regress_coremark/'
+  destination="$(dirname "${script_dir}")/data"
+
+  while :; do
+    case "${1-}" in
+    -h | --help) usage ;;
+    -v | --verbose) set -x ;;
+    --no-color) NO_COLOR=1 ;;
+    -r | --remove) remove=1 ;;
+    -s | --source)
+      param="${2-}"
+      shift
+      ;;
+    -d | --destination)
+      destination="${2-}"
+      shift
+      ;;
+    -?*) die "Unknown option: $1" ;;
+    *) break ;;
+    esac
+    shift
+  done
+
+  args=("$@")
+
+  # check required params and arguments
+  # [[ -z "${param-}" ]] && die "Missing required parameter: param"
+  # [[ ${#args[@]} -eq 0 ]] && die "Missing script arguments"
+
+  return 0
+}
+
+parse_params "$@"
+setup_colors
+
+# Scripting part
+# =============================================================================
+if [[ "${remove}" -eq 1 ]]; then
+  # Move all files from source directory to destination directory
+  mv "${source}/"* "${destination}"
+else
+  # Copy all files from source directory to destination directory
+  cp "${source}/"* "${destination}"
+fi
+
+# Extract contents of all .tar.gz files in destination directory
+for file in "${destination}"/*.tar.gz; do
+  tar -xzf "${file}" -C "${destination}"
+done
+
+# Remove .tar.gz files in the destination directory
+for file in "${destination}"/*.tar.gz; do
+  rm "${file}"
 done
